name: Auto Assign PR
on:
  pull_request:
    types: [opened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.issue.number;
            const assignee = context.payload.pull_request.user.login;
            
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number,
              assignees: [assignee]
            });
